### ISSUE TITLE
Why Windows?

### ISSUE THREAD

**Issue by bieniop** [fireeye/ThreatPursuit-VM#1]
Hi,

This is just curious question - why the dedicated platform to install tooling is Windows?

Best regards

**Comment by Jestin1702** [comment]
Why cant we use VMware or VirtualBox?

**Comment by cuevas5777** [comment]
Según he entendido tienes que crear la maquina virtual pero con el sistema Windows y ya instalarlo

**Comment by itzdan** [comment]
like FLARE VM and Commando VM, we like to keep our virtual machines consistent on the windows base. There is plans to go for a linux version. But thats more like Q1 2021.
