### ISSUE TITLE
README.md & Tool classification

### ISSUE THREAD

**Issue by WesWrench** [fireeye/ThreatPursuit-VM#10]
Hello,

Thank you very much for this project! I am in the process of installing it and everything seems to be working fine.

The question I ask myself concerns the classification of the tools present in the README.md.

Why is the "Elasticsearch" tool present in the "Development, Analytics and Machine Learning" category and not in the "Triage, Modeling & Hunting" category?

Elasticsearch (with Kibana) can be an Open Source alternative to Splunk for the triage process, right?

The other problem is the classification of the "MISP" tool.
For OpenCTI I agree with you (this one allowing to make victimology) to classify it in "Modeling".

Now regarding MISP, I don't see in any way what it does in "Triage, Modeling & Hunting":
- The MISP correlation engine does not work when there are too many IOCs, in other words unusable.
- MISP only runs on relational databases, which makes the "Triage" part complicated.

MISP only serves as a base for storing and sharing IOCs in a compliant way. By serving as a database and sharing IOCs, I do not see where MISP allows to do any step of "Triage, Modeling & Hunting".

Regarding "Coretex Analyzer", there is a small typo.

Best regards,

**Comment by itzdan** [comment]
Thanks Wes, Fixed typo in package Cortex. Ive taken your additional comments for consideration in next updates :) 

Thanks
