### ISSUE TITLE
Caldera - won't start, different from Github

### ISSUE THREAD

**Issue by jamesdeluk** [fireeye/ThreatPursuit-VM#11]
I've just installed TP on a Win 10 Enterprise VM (from [MS](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/)) on VirtualBox.

Tried to run Caldera, but the Python packages weren't installed, so I installed them.

Then running server.py:
`PS C:\Tools\Caldera > python .\server.py
DEBUG:root:Agents will be considered untrusted after 60 seconds of silence                                              DEBUG:root:Uploaded files will be put in /tmp
DEBUG:root:Serving at http://0.0.0.0:8888
DEBUG:data_svc:There are 0 jobs in the scheduler
ERROR:app_svc:Problem locating the "compass" plugin. Ensure CALDERA was cloned recursively.`

When I cloned Caldera from Github, that folder is 153MB. The TP one is only 5MB.

Am I missing something?

**Comment by itzdan** [comment]
Hi @jamesdeluk  yes the package DL'd v2.5.1, sha256 742e211c12ef13b80f0036321822e42af0294545007fe22d937170ff7dc0f566 at 5.7mb sourced from, https://github.com/mitre/caldera/archive/2.5.1.zip. I will get this updated to 2.8.1 over next few days.

You will need to follow the README.md instructions, which does require you to run pip install requirements and recursively pull further files.
