### ISSUE TITLE
Userid and passwords

### ISSUE THREAD

**Issue by syclam** [fireeye/ThreatPursuit-VM#12]
Hi,
Is there a document that lists the userid and passwords for the tools.  I tried logging to Splunk but I don't seem to have the userid and password

**Comment by itzdan** [comment]
hey @syclam , did you see the readme.txt file placed on the desktop? it should have instructions on where to find (splunk.log in %TEMP% directory) within there it will contain your randomly generated password (generated on your vm alone).
