### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by enthuss** [fireeye/ThreatPursuit-VM#14]
----                -------------         ------ ----
d-----       11/17/2020     11:01                ChocoCache
**********************
Command start time: 20201117111326
**********************
PS>TerminatingError(): "Exception calling "DeserializeObject" with "1" argument(s): "Invalid array passed in, ',' expected. (2524): {     "packages": [         {"name": "jre8"},         {"name": "openjdk11"},         {"name": "elasticsearch.fireeye"},         {"name": "kibana.fireeye"},         {"name": "splunk.fireeye"},         {"name": "maltego.fireeye"},         {"name": "Constellation.fireeye"},         {"name": "googlechrome.fireeye"},         {"name": "r"},         {"name": "rtools"},         {"name": "dotnet4.7.2"},         {"name": "cmder.fireeye"},         {"name": "git"},         {"name": "adobereader.fireeye"},         {"name": "wireshark.fireeye"},         {"name": "cyberchef.flare"},         {"name": "firefox.fireeye"},         {"name": "python3"},         {"name": "tortoisesvn"},         {"name": "sysinternals.fireeye"},         {"name": "nmap.fireeye"},         {"name": "SublimeText3.fireeye"},         {"name": "autoit.fireeye"},         {"name": "ScreenToGif.fireeye"},         {"name": "putty.fireeye"},         {"name": "vlc.fireeye"},         {"name": "7zip"},         {"name": "Greenshot.fireeye"},         {"name": "winscp.fireeye"},         {"name": "keepass.fireeye"},         {"name": "vnc-viewer.fireeye"},         {"name": "shogun.fireeye"},         {"name": "spark.fireeye"},         {"name": "Jupyter.fireeye"},         {"name": "orbit.fireeye"},         {"name": "caldera.fireeye"},         {"name": "ctiattack.fireeye"},         {"name": "APTSimulator.fireeye"},         {"name": "flightsim.fireeye"},         {"name": "opencti.fireeye"},         {"name": "spiderfoot.fireeye"},         {"name": "yara.flare"},         {"name": "xorsearch.flare"},         {"name": "xorstrings.flare"},         {"name": "tor-browser.fireeye"},         {"name": "zeppelin.fireeye"},         {"name": "MISP.fireeye"},         {"name": "keras.fireeye"},         {"name": "darwin.fireeye"},         {"name": "msticpy.fireeye"},         {"name": "threathuntersplaybook.fireeye"},         {"name": "mordor.fireeye"},         {"name": "coretex.fireeye"},         {"name": "azurezentinel.fireeye"},         {"name": "greynoise.fireeye"},         {"name": "attackcti.fireeye"},         {"name": "taxiiclient.fireeye"},         {"name": "harpoon.fireeye"},         {"name": "ctipythonstix.fireeye"},         {"name": "yeti.fireeye"},         {"name": "cmaptools"},         {"name": "eqllib.fireeye"},         {"name": "bzar.fireeye"},         {"name": "msthreathunt.fireeye"},         {"name": "sigma.fireeye"},         {"name": "amittframework.fireeye"},         {"name": "hashcheck"},         {"name": "atomicredteam.fireeye"}         {"name": "atomictestharness.fireeye"}         {"name": "neo4j-community.fireeye", "x64Only": true},         {"name": "peview.flare"},         {"name": "notepadplusplus", "args": "--x86"},         {"name": "notepadplusplus-textfx.fireeye"},         {"name": "hxd.fireeye"},         {"name": "SilkETW.fireeye"},         {"name": "unxUtils"},         {"name": "flare-floss.fireeye"},         {"name": "gowitness.fireeye","x64Only": true},         {"name": "dnsrecon.fireeye"},         {"name": "FOCA.fireeye"},         {"name": "docker.fireeye"},         {"name": "chromebookmarkstpvm.fireeye"},         {"name": "shortcutstpvm.fireeye"},         {"name": "openvpn.fireeye", "args":"--parameters \'/SELECT_SHORTCUTS=0 /SELECT_LAUNCH=0\'"}     ] }""
Packages property not found! Exiting
-1
DEBUG: ----------------------------------------------------------------------

**Comment by itzdan** [comment]
Missing "," char in install 1.6 

Have pushed 1.7 package to myget reflecting the git repo. 

Issue should now be fixed. Please try reinstall "choco upgrade'
