### ISSUE TITLE
MITRE TRAM

### ISSUE THREAD

**Issue by phate1** [fireeye/ThreatPursuit-VM#18]
Hey

was looking for MITRE TRAM in Threatpursuit but couldn't find any sign of it or mentions of it in the packages. am I missing something obvious or is it not currently being installed? cheers

**Comment by itzdan** [comment]
@phate1  nope you are right its missing. we had a version overwrite last few days over at myget.org,  I am just in the process of recovering the latest version (1.7)  i'll add MITRE TRAM back in. and respond back to this message. thanks

**Comment by itzdan** [comment]
for testing, can be installed manually using `choco install tram.fireeye`
