### ISSUE TITLE
Package not found in the source

### ISSUE THREAD

**Issue by nortonpt** [fireeye/ThreatPursuit-VM#2]
Lots of packagers arent found in the sources provided.

Will you update the links?

**Comment by s1nglethr3ad** [comment]
myget.org goes down sometimes.  Fireeye hosts their repo there.

https://www.isitdownrightnow.com/myget.org.html

**Comment by itzdan** [comment]
yes myget.org had some issues over the past weekend which resulted in a number of us not being able to download. Most of their services have been up for past 42 hours so we should be good to go 👍
