### ISSUE TITLE
Failed to install azurezentinel.fireeye

### ISSUE THREAD

**Issue by darioongit** [fireeye/ThreatPursuit-VM#21]
azurezentinel.fireeye is not installed. Installing...
azurezentinel.fireeye not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/"

Chocolatey upgraded 0/1 packages. 1 packages failed.

Failures
 - azurezentinel.fireeye - azurezentinel.fireeye not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/"

**Comment by itzdan** [comment]
added back in and updated to new version

test using (powershell elevated)

`choco install azurezentinel.fireeye `
