### ISSUE TITLE
Failed to install ctiattack.fireeye

### ISSUE THREAD

**Issue by darioongit** [fireeye/ThreatPursuit-VM#23]
ctiattack.fireeye v6.2
ctiattack.fireeye package files upgrade completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was 'F76B9066F9230859D63BF822999E818E7313CC9BA997AD1A63CD86CB009143D48D99C08BB3E46E1C9F4F2113D1906FF3601B2BC3B90A1DB78CF7BC1C394BD45A'.
Downloading ctiattack.fireeye
  from 'https://github.com/microsoft/msticpy/archive/v0.7.0.zip'
Error - hashes do not match. Actual value was 'F76B9066F9230859D63BF822999E818E7313CC9BA997AD1A63CD86CB009143D48D99C08BB3E46E1C9F4F2113D1906FF3601B2BC3B90A1DB78CF7BC1C394BD45A'.
ERROR: Checksum for 'C:\Users\myadmin\AppData\Local\ChocoCache\ctiattack.fireeye\6.2\msticpy-0.7.0.zip' did not meet '1f76f6edb819a7d3277cb2b3ec588129d9cb89af4d5417b7ac3b906b346776f7' for checksum type 'sha512'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The upgrade of ctiattack.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\ctiattack.fireeye\Tools\chocolateyInstall.ps1'.

Failures
 - ctiattack.fireeye (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\ctiattack.fireeye\Tools\chocolateyInstall.ps1'.

**Comment by itzdan** [comment]
I see that the script is trying to verify a SHA256 hash against a SHA512,  PR raised in dev to change to SHA256.

**Comment by itzdan** [comment]
Resolved
