### ISSUE TITLE
Using a Linux Workstation Using VirtualBox/VMWare

### ISSUE THREAD

**Issue by PandaLyfe** [fireeye/ThreatPursuit-VM#29]
Is there anyone using a Linux workstation tried to install ThreatPursuit on either VMWare Workstation Pro or VirtualBox? I have tried to follow the instructions exactly, but I always encounter an issue with the Docker Install. For anyone with success, I would really appreciate any advice.

**Comment by itzdan** [comment]
hey @PandaLyfe , VMware Workstation is your best bet for Docker support compatibility. You will need to ensure your virtualisation counters are enabled also within your VMware configuration and physical host (BIOS).
