### ISSUE TITLE
Unavailable services

### ISSUE THREAD

**Issue by chrswtsn** [fireeye/ThreatPursuit-VM#3]
Splunk works but it is configured with an unknown username & password. Tried running Jupyter notebooks with  'jupyter notebook' and got it is not a recognized command so it will not start. I checked docker containers and I see nothing is in there, I'm assuming it is needed to run ELK, beyond that navigating to localhost:5601 does not work.  Also tried MISP, not sure what port it is configured to run on, regular port 80 does not return a page. Can you provide some instructions for turning on these services, credentials where needed etc.  Maybe a more detailed readme?

**Comment by teixeira0xfffff** [comment]
Its how to reset splunk admin password: https://community.splunk.com/t5/Security/Splunk-Admin-Password/m-p/326020

**Comment by chrswtsn** [comment]
Thanks for the feed back this worked for splunk.  Any suggestions for Jupyter notebook, misp, and ELK? I understand each tool has it's own documentation but how they were implemented in this script is unclear. As an example I have misp running on ubuntu 18.04 and it only reguires navigating to localhost or http://localhost/user/login.

**Comment by itzdan** [comment]
> Thanks for the feed back this worked for splunk, I also got Jupyter working. Tools are downloaded but I guess not configured. Some of the scripts are failing for docker like OpenCTI, and MISP. see below:
> 
> MISP:
> `E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 20h 58min 47s). Updates for this repository will not be applied. E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 20h 59min 28s). Updates for this repository will not be applied. E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 21h 0min 18s). Updates for this repository will not be applied. ERROR: Service 'web' failed to build : The command '/bin/sh -c apt-get update && apt-get dist-upgrade -y && apt-get autoremove -y && apt-get clean && apt-get install -y software-properties-common && apt-get install -y postfix && apt-get install -y mysql-client curl gcc git gnupg-agent make python openssl redis-server sudo vim zip locales' returned a non-zero code: 100`
> 
> OpenCTI:
> 
> `c0c70fbb7236: Extracting [==============> ] 30.08MB/103.4MB ERROR: Bad response from Docker engine`

hey chrswtsn,

Thanks for sending that through, a few good points/issues you've raised that we will get looked into..

1. Firstly I couldn't reproduce that specific docker container error with 0.1 build on Win10 2004. 
 
run cmd.exe as an Administrator and do the following;
`docker run -d -p 80:80 docker/getting-started`  and check if this image gets built and runs correctly. _then stop the container and move on._
`cd C:\Tools\MISP\ `
`docker-compose --compatibility up` 

Were you able to pull down the images? after a period of time, do you see the containers running?  were there any errors?

Make sure you allocate enough memory resources dedicated to running your containers. Each containers as per readme.md do need their own configuration to run correctly. It's tedious however necessary. 

2. Both MISP and OpenCTI might be out of date slightly.. and will be updated over the next day.. 

3. The install credentials for Splunk panel are randomly generated during the install on your client, and are kept in your %TEMP% folder.

4. Will have a basic readme and instruction guide together to help out with those first few steps, e.g Splunk and Docker setup. That will come in a small update by mid next week.
