### ISSUE TITLE
Consider adding IntelOwl to installed applications

### ISSUE THREAD

**Issue by mlodic** [fireeye/ThreatPursuit-VM#4]
Hi! First I would like to thank you for this project. It is really awesome.

Would you consider the addition of [IntelOwl](https://github.com/intelowlproject/IntelOwl) in the list of the pre-installed tools? IntelOwl can be useful for threat intel analysts and is complementary to other installed tools like OpenCTI or MISP. Thoughts?

**Comment by itzdan** [comment]
> Hi! First I would like to thank you for this project. It is really awesome.
> 
> Would you consider the addition of [IntelOwl](https://github.com/intelowlproject/IntelOwl) in the list of the pre-installed tools? IntelOwl can be useful for threat intel analysts and is complementary to other installed tools like OpenCTI or MISP. Thoughts?

I think thats a great idea mlodic. I'll tee it up to add in for 0.2 dropping around mid next week.

**Comment by mlodic** [comment]
Obviously we are here to help if you need! :)

**Comment by itzdan** [comment]
hey @mlodic  sorry about this totally smashed past ~2 weeks. I have just added intelowl into dev branch, it is getting QA'd atm. should be into prod next day or so, and will be placed under Information Gathering Folder. I am using your latest version 1.9.0 :) 

You can run an install manually via the following

`choco install intelowl.fireeye `

**Comment by mlodic** [comment]
that's great :heart:  thank you for your great work!
