### ISSUE TITLE
Successful Installation Indication

### ISSUE THREAD

**Issue by pferrill** [fireeye/ThreatPursuit-VM#8]
How do you know if everything installed correctly?

Is there a log file somewhere?

Are there any additional steps after the ps1 script completes?

**Comment by jamesdeluk** [comment]
Also think this would be really useful, as I've just installed TP a couple times on different VMs but I did see flashes of red throughout and I don't think everything is working.

**Comment by itzdan** [comment]
added readme.txt to desktop
